version: "2.0"

services:
  postgresql:
    build:
      context: postgres
      dockerfile: Dockerfile.dev
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=expman
      - POSTGRES_PASSWORD=qqq
    volumes:
      - "db-data:/var/lib/postgresql/data"
  expman-server:
    build:
      context: expman-server
      dockerfile: Dockerfile.dev
      args:
        - PORT=8081
    environment:
      - PORT=8081
      - DATABASE_URL=postgres://user:qqq@postgresql/expman
    ports:
      - 8081:8081
    depends_on:
      - postgresql
    volumes:
      - ./expman-server:/usr/src/expman

volumes:
   db-data:
